//--------------------------------------------------------------------------------
// Auto-generated by Migen (0fc94be) & LiteX (a98986ec) on 2021-09-11 19:09:32
//--------------------------------------------------------------------------------
module top(
	input wire altera_reserved_tms,
	input wire altera_reserved_tck,
	input wire altera_reserved_tdi,
	output wire altera_reserved_tdo,
	input wire sys_clk,
	input wire sys_rst
);

reg jtag_phy_reset = 1'd0;
reg jtag_phy_capture = 1'd0;
wire jtag_phy_shift;
wire jtag_phy_update;
wire jtag_phy_runtest;
wire jtag_phy_drck;
wire jtag_phy_sel;
wire jtag_phy_tck;
wire jtag_phy_tms;
wire jtag_phy_tdi;
wire jtag_phy_tdo;
wire jtag_phy_altera_reserved_tck;
wire jtag_phy_altera_reserved_tms;
wire jtag_phy_altera_reserved_tdi;
wire jtag_phy_altera_reserved_tdo;
reg jtag_phy_tdouser = 1'd0;
reg jtag_phy_tmscore = 1'd0;
reg jtag_phy_tckcore = 1'd0;
reg jtag_phy_tdicore = 1'd0;
wire jtag_phy_tmsutap;
wire jtag_phy_tckutap;
wire jtag_phy_tdiutap;
wire jtag_phy_tdocore;
wire jtag_inv_clk;
wire jtag_inv_rst;
reg jtag_phy_is_ongoing0 = 1'd1;
wire jtag_phy_TEST_LOGIC_RESET;
reg jtag_phy_is_ongoing1 = 1'd0;
wire jtag_phy_RUN_TEST_IDLE;
reg jtag_phy_is_ongoing2 = 1'd0;
wire jtag_phy_SELECT_DR_SCAN;
reg jtag_phy_is_ongoing3 = 1'd0;
wire jtag_phy_CAPTURE_DR;
reg jtag_phy_is_ongoing4 = 1'd0;
wire jtag_phy_SHIFT_DR;
reg jtag_phy_is_ongoing5 = 1'd0;
wire jtag_phy_EXIT1_DR;
reg jtag_phy_is_ongoing6 = 1'd0;
wire jtag_phy_PAUSE_DR;
reg jtag_phy_is_ongoing7 = 1'd0;
wire jtag_phy_EXIT2_DR;
reg jtag_phy_is_ongoing8 = 1'd0;
wire jtag_phy_UPDATE_DR;
reg jtag_phy_is_ongoing9 = 1'd0;
wire jtag_phy_SELECT_IR_SCAN;
reg jtag_phy_is_ongoing10 = 1'd0;
wire jtag_phy_CAPTURE_IR;
reg jtag_phy_is_ongoing11 = 1'd0;
wire jtag_phy_SHIFT_IR;
reg jtag_phy_is_ongoing12 = 1'd0;
wire jtag_phy_EXIT1_IR;
reg jtag_phy_is_ongoing13 = 1'd0;
wire jtag_phy_PAUSE_IR;
reg jtag_phy_is_ongoing14 = 1'd0;
wire jtag_phy_EXIT2_IR;
reg jtag_phy_is_ongoing15 = 1'd0;
wire jtag_phy_UPDATE_IR;
wire jtag_clk;
wire jtag_rst;
wire hello_tdo;
reg [31:0] hello_dr = 32'd2852192085;
wire hello_inner_tdo;
reg [3:0] state = 4'd0;
reg [3:0] next_state = 4'd0;
wire ars_cd_jtag_rst_meta;

assign jtag_clk = jtag_phy_tck;
assign jtag_phy_tdo = hello_tdo;
assign jtag_inv_clk = (~jtag_clk);
assign jtag_inv_rst = jtag_rst;
assign jtag_phy_altera_reserved_tms = altera_reserved_tms;
assign jtag_phy_altera_reserved_tck = altera_reserved_tck;
assign jtag_phy_altera_reserved_tdi = altera_reserved_tdi;
assign altera_reserved_tdo = jtag_phy_altera_reserved_tdo;
assign jtag_phy_tck = jtag_phy_tckutap;
assign jtag_phy_tms = jtag_phy_tmsutap;
assign jtag_phy_tdi = jtag_phy_tdiutap;
assign jtag_phy_TEST_LOGIC_RESET = jtag_phy_is_ongoing0;
assign jtag_phy_RUN_TEST_IDLE = jtag_phy_is_ongoing1;
assign jtag_phy_SELECT_DR_SCAN = jtag_phy_is_ongoing2;
assign jtag_phy_CAPTURE_DR = jtag_phy_is_ongoing3;
assign jtag_phy_SHIFT_DR = jtag_phy_is_ongoing4;
assign jtag_phy_EXIT1_DR = jtag_phy_is_ongoing5;
assign jtag_phy_PAUSE_DR = jtag_phy_is_ongoing6;
assign jtag_phy_EXIT2_DR = jtag_phy_is_ongoing7;
assign jtag_phy_UPDATE_DR = jtag_phy_is_ongoing8;
assign jtag_phy_SELECT_IR_SCAN = jtag_phy_is_ongoing9;
assign jtag_phy_CAPTURE_IR = jtag_phy_is_ongoing10;
assign jtag_phy_SHIFT_IR = jtag_phy_is_ongoing11;
assign jtag_phy_EXIT1_IR = jtag_phy_is_ongoing12;
assign jtag_phy_PAUSE_IR = jtag_phy_is_ongoing13;
assign jtag_phy_EXIT2_IR = jtag_phy_is_ongoing14;
assign jtag_phy_UPDATE_IR = jtag_phy_is_ongoing15;
always @(*) begin
	jtag_phy_is_ongoing10 <= 1'd0;
	next_state <= 4'd0;
	jtag_phy_is_ongoing11 <= 1'd0;
	jtag_phy_is_ongoing12 <= 1'd0;
	jtag_phy_is_ongoing0 <= 1'd1;
	jtag_phy_is_ongoing13 <= 1'd0;
	jtag_phy_is_ongoing1 <= 1'd0;
	jtag_phy_is_ongoing14 <= 1'd0;
	jtag_phy_is_ongoing2 <= 1'd0;
	jtag_phy_is_ongoing15 <= 1'd0;
	jtag_phy_is_ongoing3 <= 1'd0;
	jtag_phy_is_ongoing4 <= 1'd0;
	jtag_phy_is_ongoing5 <= 1'd0;
	jtag_phy_is_ongoing6 <= 1'd0;
	jtag_phy_is_ongoing7 <= 1'd0;
	jtag_phy_is_ongoing8 <= 1'd0;
	jtag_phy_is_ongoing9 <= 1'd0;
	next_state <= state;
	case (state)
		1'd1: begin
			if (jtag_phy_tms) begin
				next_state <= 2'd2;
			end
			jtag_phy_is_ongoing1 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		2'd2: begin
			if ((~jtag_phy_tms)) begin
				next_state <= 2'd3;
			end else begin
				next_state <= 4'd9;
			end
			jtag_phy_is_ongoing2 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		2'd3: begin
			if ((~jtag_phy_tms)) begin
				next_state <= 3'd4;
			end else begin
				next_state <= 3'd5;
			end
			jtag_phy_is_ongoing3 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		3'd4: begin
			if (jtag_phy_tms) begin
				next_state <= 3'd5;
			end
			jtag_phy_is_ongoing4 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		3'd5: begin
			if ((~jtag_phy_tms)) begin
				next_state <= 3'd6;
			end else begin
				next_state <= 4'd8;
			end
			jtag_phy_is_ongoing5 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		3'd6: begin
			if (jtag_phy_tms) begin
				next_state <= 3'd7;
			end
			jtag_phy_is_ongoing6 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		3'd7: begin
			if (jtag_phy_tms) begin
				next_state <= 4'd8;
			end else begin
				next_state <= 3'd4;
			end
			jtag_phy_is_ongoing7 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		4'd8: begin
			if (jtag_phy_tms) begin
				next_state <= 2'd2;
			end else begin
				next_state <= 1'd1;
			end
			jtag_phy_is_ongoing8 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		4'd9: begin
			if ((~jtag_phy_tms)) begin
				next_state <= 4'd10;
			end else begin
				next_state <= 1'd0;
			end
			jtag_phy_is_ongoing9 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		4'd10: begin
			if ((~jtag_phy_tms)) begin
				next_state <= 4'd11;
			end else begin
				next_state <= 4'd12;
			end
			jtag_phy_is_ongoing10 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		4'd11: begin
			if (jtag_phy_tms) begin
				next_state <= 4'd12;
			end
			jtag_phy_is_ongoing11 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		4'd12: begin
			if ((~jtag_phy_tms)) begin
				next_state <= 4'd13;
			end else begin
				next_state <= 4'd15;
			end
			jtag_phy_is_ongoing12 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		4'd13: begin
			if (jtag_phy_tms) begin
				next_state <= 4'd14;
			end
			jtag_phy_is_ongoing13 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		4'd14: begin
			if (jtag_phy_tms) begin
				next_state <= 4'd15;
			end else begin
				next_state <= 4'd11;
			end
			jtag_phy_is_ongoing14 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		4'd15: begin
			if (jtag_phy_tms) begin
				next_state <= 2'd2;
			end else begin
				next_state <= 1'd1;
			end
			jtag_phy_is_ongoing15 <= 1'd1;
			jtag_phy_is_ongoing0 <= 1'd0;
		end
		default: begin
			if ((~jtag_phy_tms)) begin
				next_state <= 1'd1;
			end
			jtag_phy_is_ongoing0 <= 1'd1;
		end
	endcase
end
assign hello_tdo = hello_inner_tdo;
assign hello_inner_tdo = hello_dr[0];

always @(posedge jtag_clk) begin
	state <= next_state;
	if ((jtag_phy_reset | jtag_phy_capture)) begin
		hello_dr <= 32'd2852192085;
	end else begin
		if (jtag_phy_shift) begin
			hello_dr <= {jtag_phy_tdiutap, hello_dr[31:1]};
		end
	end
	if (jtag_rst) begin
		hello_dr <= 32'd2852192085;
		state <= 4'd0;
	end
end

always @(posedge jtag_inv_clk) begin
	jtag_phy_reset <= jtag_phy_TEST_LOGIC_RESET;
	jtag_phy_capture <= jtag_phy_CAPTURE_DR;
	jtag_phy_tdouser <= jtag_phy_tdo;
	if (jtag_inv_rst) begin
		jtag_phy_reset <= 1'd0;
		jtag_phy_capture <= 1'd0;
		jtag_phy_tdouser <= 1'd0;
	end
end

fiftyfivenm_jtag fiftyfivenm_jtag(
	.tck(jtag_phy_altera_reserved_tck),
	.tckcore(jtag_phy_tckcore),
	.tdi(jtag_phy_altera_reserved_tdi),
	.tdicore(jtag_phy_tdicore),
	.tdouser(jtag_phy_tdouser),
	.tms(jtag_phy_altera_reserved_tms),
	.tmscore(jtag_phy_tmscore),
	.clkdruser(jtag_phy_drck),
	.runidleuser(jtag_phy_runtest),
	.shiftuser(jtag_phy_shift),
	.tckutap(jtag_phy_tckutap),
	.tdiutap(jtag_phy_tdiutap),
	.tdo(jtag_phy_altera_reserved_tdo),
	.tdocore(jtag_phy_tdocore),
	.tmsutap(jtag_phy_tmsutap),
	.updateuser(jtag_phy_update),
	.usr1user(jtag_phy_sel)
);

DFF ars_cd_jtag_ff0(
	.clk(jtag_clk),
	.clrn(1'd1),
	.d(1'd0),
	.prn((~sys_rst)),
	.q(ars_cd_jtag_rst_meta)
);

DFF ars_cd_jtag_ff1(
	.clk(jtag_clk),
	.clrn(1'd1),
	.d(ars_cd_jtag_rst_meta),
	.prn((~sys_rst)),
	.q(jtag_rst)
);

endmodule


